### ISSUE TITLE
criteria for making pullrequests

### ISSUE THREAD

**Issue by razzat008** [ComputeNepal/learn-c-programming#9]
Please add a section for the criteria that must be fulfilled before making any pull-requests.

The criteria can contain something like:
- Descriptive names
- Well commented code
- Descriptive commit
- Well documented readme.me

I think this will help in creating a healthy environment for new contributors.

**Comment by razzat008** [comment]
I hope these will be considered in the future.

**Comment by gauravfs-14** [comment]
Implemented. Thanks for the feedback.
